name: 🚀 Deploy UI da conta
on: 
  push:
    branches:
      - deploy
jobs:
  Web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with: 
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.binga.ao
        username: bingaao@conta.binga.ao
        password: 00antesdemimDeus
